### ISSUE TITLE
Slice error list

### ISSUE THREAD

**Issue by sumcoinlabs** [CryptoCloudInc/slicewallet-android#1]
@losh11 

I sent you a DM on twitter but there are a few minor fixes needed and one major issue needing resolved as quickly as possible.

Major:
Cannot send coin out of wallet and unsure why.  Segwit or Legacy both fail with assertion shown below

![image](https://user-images.githubusercontent.com/37975862/56169077-447a9f80-5f9a-11e9-8a6c-19bc61d882f0.png)

Minor
1.  On Display currency in settings, "lites" should be "mSums" 
2.  EUR does not load any rates.
3.  When support is clicked in settings it returns 404
4.  When Security Center is clicked, the app force closes

Please advise

**Comment by losh11** [comment]
Fixed all (except 4 since that's only occurring on your specific device).

**Comment by CryptoCloudInc** [comment]
04-16 19:18:02.772 26022-26088/com.slicewallet I/bread: 165.227.23.67:3333 calling getblocks with 2 locators: [331b3eb79dc74bcb0cab9d929ffac094ba146f0432bf4bc7e03f946b682ce8d0, 14eab7272010942a839325e478f5dcd33e25637c88f1927e95d0eee5a5fb451e]
04-16 19:18:02.772 26022-26088/com.slicewallet I/bread: 165.227.23.67:3333 sending getblocks
04-16 19:18:02.987 26022-26022/com.slicewallet D/ViewRootImpl@f662fb2[BreadActivity]: ViewPostIme pointer 0
04-16 19:18:03.110 26022-26022/com.slicewallet D/ViewRootImpl@f662fb2[BreadActivity]: ViewPostIme pointer 1
04-16 19:18:03.139 26022-26047/com.slicewallet V/FA: Recording user engagement, ms: 8556
04-16 19:18:03.141 26022-26047/com.slicewallet V/FA: Connecting to remote service
04-16 19:18:03.146 26022-26047/com.slicewallet V/FA: Activity paused, time: 7852549
04-16 19:18:03.152 26022-26047/com.slicewallet D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=8556, firebase_screen_class(_sc)=BreadActivity, firebase_screen_id(_si)=-4168049547029141648}]
04-16 19:18:03.166 26022-26047/com.slicewallet V/FA: Connection attempt already in progress
04-16 19:18:03.167 26022-26045/com.slicewallet E/FirebaseCrash: Firebase Crash Reporting not enabled
04-16 19:18:03.176 26022-26022/com.slicewallet V/FA: onActivityCreated
04-16 19:18:03.239 26022-26022/com.slicewallet W/SystemServiceRegistry: No service published for: fingerprint
04-16 19:18:03.241 26022-26022/com.slicewallet D/AndroidRuntime: Shutting down VM
04-16 19:18:03.245 26022-26022/com.slicewallet E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.slicewallet, PID: 26022
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.slicewallet/com.breadwallet.presenter.activities.settings.SecurityCenterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
                                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
                                                                     at com.breadwallet.tools.util.Utils.isFingerprintEnrolled(Utils.java:191)
                                                                     at com.breadwallet.presenter.activities.settings.SecurityCenterActivity.updateList(SecurityCenterActivity.java:169)
                                                                     at com.breadwallet.presenter.activities.settings.SecurityCenterActivity.onCreate(SecurityCenterActivity.java:73)
                                                                     at android.app.Activity.performCreate(Activity.java:7183)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
                                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                     at android.os.Looper.loop(Looper.java:164) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6944) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
04-16 19:18:03.247 26022-26022/com.slicewallet E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.slicewallet/com.breadwallet.presenter.activities.settings.SecurityCenterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
                                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
                                                                        at com.breadwallet.tools.util.Utils.isFingerprintEnrolled(Utils.java:191)
                                                                        at com.breadwallet.presenter.activities.settings.SecurityCenterActivity.updateList(SecurityCenterActivity.java:169)
                                                                        at com.breadwallet.presenter.activities.settings.SecurityCenterActivity.onCreate(SecurityCenterActivity.java:73)
                                                                        at android.app.Activity.performCreate(Activity.java:7183)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
                                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6944) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
04-16 19:18:03.248 26022-26045/com.slicewallet E/FirebaseCrash: Firebase Crash Reporting not enabled

**Comment by losh11** [comment]
https://stackoverflow.com/questions/36031092/fingerprintmanager-ishardwaredetected-throwing-java-lang-securityexception

Try cleaning and rebuilding to your device.
